services:
  backend:
    build:
      context: ./note-nexus-backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    image: saisriharsha2005/note-nexus-backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./note-nexus-backend:/note-nexus-backend
      - /note-nexus-backend/node_modules  
    networks:
      - network
    ports:
      - 8080:8080

  frontend:
    build: 
      context: ./note-nexus-frontend
      dockerfile: Dockerfile.dev
    image: saisriharsha2005/note-nexus-frontend
    restart: unless-stopped
    volumes: 
      - ./note-nexus-frontend:/note-nexus-frontend
      - /note-nexus-frontend/node_modules  
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - network
    env_file: ./note-nexus-frontend/.env
    depends_on:
      - backend
    ports:
      - 3000:5173

networks:
  network:
    driver: bridge
