name: "saisriharsha/note-nexus"

services:
  backend:
    build:
      context: ./note-nexus-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: ./note-nexus-backend/.env
    volumes:
      - ./note-nexus-backend:/note-nexus/backend
    networks:
      - network
    ports:
      - 8080:8080

  frontend:
    build: 
      context: ./note-nexus-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes: 
      - ./note-nexus-frontend:/note-nexus/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - network
    env_file: ./note-nexus-frontend/.env
    depends_on:
      - backend
    ports:
      - 3000:3000

networks:
  network:
    driver: bridge
