apiVersion: v1 
kind: Service
metadata:
  name: note-nexus-frontend-service
  labels:
    type: note-nexus-frontend_service
spec:
  selector:
      tier: note-nexus-frontend_pod
  type: NodePort
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 30080
  