apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-nexus-frontend-deployment
  labels:
    tier: note-nexus-frontend_deployment
spec:
  template:
    metadata:
      name: note-nexus-frontend-pod
      labels:
        tier: note-nexus-frontend_pod
    spec:
      containers:
        - name: note-nexus-frontend
          image: saisriharsha2005/note-nexus-frontend:latest
          env:
          - name: CHOKIDAR_USEPOLLING
            value: "true"
          ports:
          - containerPort: 5173
  replicas: 2
  selector:
    matchLabels: 
      tier: note-nexus-frontend_pod
      


