# Stage 1: Base Image for Development
FROM alpine:3.18 AS development

# Install Node.js, npm, and other necessary tools
RUN apk add --no-cache nodejs npm

# Set the working directory
WORKDIR /note-nexus/backend/

# Copy only package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install --no-cache && npm install -g nodemon

# Copy only necessary source files
COPY . .

# Expose the React development server port
EXPOSE 8080

# Command to run the development server with hot reloading
CMD ["npm", "start"]
