apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-nexus-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-nexus_backend
  template:
    metadata:
      labels:
        app: note-nexus_backend
    spec:
      containers:
        - name: note-nexus-backend
          image: saisriharsha2005/note-nexus-backend:latest
          ports:
            - containerPort: 8080

