apiVersion: v1
kind: Service
metadata: 
  name: note-nexus-backend-service
  labels: 
    type: note-nexus-backend_service
spec: 
  selector:
      tier: note-nexus-backend_pod
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081